version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"  # Replace with your GitHub username
    assignees:
      - "your-github-username"  # Replace with your GitHub username
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    groups:
      # Group React-related updates
      react:
        patterns:
          - "react*"
          - "@types/react*"
      # Group Next.js related updates
      nextjs:
        patterns:
          - "next"
          - "@next/*"
      # Group testing related updates
      testing:
        patterns:
          - "jest"
          - "@testing-library/*"
          - "@types/jest"
      # Group linting and formatting tools
      dev-tools:
        patterns:
          - "eslint*"
          - "prettier"
          - "@typescript-eslint/*"
          - "husky"
          - "lint-staged"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"

  # Enable version updates for Docker if you have Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "automated"
