# Network Configuration
httpTimeout: 300000  # 5 minute timeout (60000 = 1 minute default)
httpRetry: 5         # Retry failed requests up to 5 times
networkConcurrency: 15 # Balance between speed and overwhelming connections
npmRegistryServer: "https://registry.yarnpkg.com"

# Cache Settings
enableGlobalCache: true
cacheFolder: "./.yarn/cache"
compressionLevel: 0  # Faster installs (9 for maximum compression)

# Installation Behavior
nodeLinker: "node-modules" # More compatible with ecosystem
nmMode: "classic"         # Traditional file copying
enableScripts: true       # Allow postinstall scripts
enableImmutableInstalls: false # Allow lockfile updates
enableConstraintsChecks: false # Disable constraints for faster installs

# Performance Optimizations
taskPoolConcurrency: 8    # Match your CPU cores
taskPoolMode: "workers"   # Parallel processing
enableProgressBars: true  # Visual feedback
enableTimers: true        # Show timing information

# Security
enableStrictSsl: true     # Verify SSL certificates
enableHardenedMode: false # Disable for development speed
unsafeHttpWhitelist: []   # No HTTP exceptions

# Development Features
enableColors: true        # Colorful output
enableHyperlinks: true    # Clickable links in terminal
enableMessageNames: true  # Better error messages
preferInteractive: true   # Helpful prompts
pnpMode: "strict"        # If using PnP

# Telemetry (optional)
enableTelemetry: false    # Disabled for privacy

# Workspace Settings
enableTransparentWorkspaces: true
nmHoistingLimits: "none"  # Default hoisting behavior

# Windows-specific
winLinkType: "junctions"  # Better Windows compatibility

# Fallback Settings
pnpFallbackMode: "dependencies-only" # If using PnP
