
name: Test CLI Installers

on:
  workflow_dispatch:  # manual trigger
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run Linux installer (dry-run)
        run: |
          chmod +x ./app/scripts/linux-cli.sh
          bash ./app/scripts/linux-cli.sh --dry-run

      - name: Run Linux installer (real)
        run: |
          bash ./app/scripts/linux-cli.sh
          # Call binary directly, don’t rely on PATH in CI
          ~/.local/bin/nextdeploy --help || (echo "Binary not found" && exit 1)

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run macOS installer (dry-run)
        run: |
          chmod +x ./app/scripts/mac-cli.sh
          bash ./app/scripts/mac-cli.sh --dry-run

      - name: Run macOS installer (real)
        run: |
          bash ./app/scripts/mac-cli.sh
          ~/.local/bin/nextdeploy --help || (echo "Binary not found" && exit 1)

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run Windows installer
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          ./app/scripts/windows.ps1

          $binPath = "$env:USERPROFILE\.local\bin\nextdeploy.exe"
          if (Test-Path $binPath) {
            & $binPath --help
          } else {
            Write-Error "Binary not found at $binPath"
            exit 1
          }
